name = "Piccolo"
uuid = "c4671d76-df94-11ed-2057-43d4fd632fad"
authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
NamedTrajectories = "538bc3a1-5ab9-4fc3-b776-35ca1e893e08"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
QuantumCollocation = "0dc23a59-5ffb-49af-b6bd-932a8ae77adf"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TrajectoryIndexingUtils = "6dad8b7f-dd9a-4c28-9b70-85b9a079bfc8"

[compat]
Reexport = "1.2"
TrajectoryIndexingUtils = "0.1"
QuantumCollocation = "0.1"
julia = "1.8"
