name: External Meta Update Recieve
on:
  repository_dispatch:
    types: [meta-update-qc]
jobs:
  MetaUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      
